# Generated by Django 3.2.7 on 2021-09-12 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("course", "0002_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["-modified_date"],
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ["-modified_date"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["-modified_date"]},
        ),
    ]
