version: "3"

services:
  app:
    build:
      context: .
      dockerfile: app/app.dockerfile
    volumes:
      - ./app:/app
    ports:
      - 8000:8000
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    volumes:
      - ./db/data:/var/lib/mysql
    env_file:
      - db/db.env

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=db
    depends_on:
      - db
    ports:
      - 8080:80
