# Generated by Django 3.2.7 on 2021-09-17 16:51

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "chapter_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Chapter"),
                            ("heading", "Heading Chapter"),
                            ("video", "Video Chapter"),
                            ("link", "Link Chapter"),
                        ],
                        max_length=255,
                    ),
                ),
                ("index", models.IntegerField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_date", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="course.course",
                    ),
                ),
                (
                    "parent_chapter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="childchapters",
                        to="chapter.chapter",
                    ),
                ),
            ],
        ),
    ]
